[package]
name = "stratos"
version = "0.1.0"
authors = ["Lennart Heinrich <lennart@ltheinrich.de>"]
edition = "2018"
license = "ISC"
repository = "https://github.com/ltheinrich/stratos"
description = "Stratosphere balloon log analyzer"
readme = "README.md"

[dependencies]
kern = "1"
plotlib = "0.4.0"

[profile.release]
lto = true
codegen-units = 1
